[package]
name = "p5"
version = "0.1.0"
authors = ["suzu6 <y.suzumura0604@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
processing = "0.3.2"
num-traits = "0.2.14"
time = "0.2.26"
rand = "0.8.3"